package LeetCode.Youtube;

import java.util.HashMap;

public class FindTheDifference {
  /*
  *
  * Given two strings s and t which consist of only lowercase letters.
    String t is generated by random shuffling string s and then add one more letter at a random position.

    Find the letter that was added in t.

    Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.
  */

  public char findTheDifference(String s, String t) {
    HashMap<Character, Integer> map = new HashMap<>();
    for(Character c : s.toCharArray()) {
      if (map.containsKey(c)) {
        map.put(c, map.getOrDefault(c, 0) + 1);
      } else {
        map.put(c, 1);
      }
    }

    for(Character c: t.toCharArray()) {
      if(!map.containsKey(c) || map.get(c) == 0) {
        return c;
      } else {
        map.put(c, map.get(c) - 1);
      }
    }
    return '!';
  }
}

class TestFindTheDifference {
  public static void main(String[] args) {
    FindTheDifference findTheDifference = new FindTheDifference();
  }
}
